### ISSUE TITLE
Brain tumor segmentation 

### ISSUE THREAD

**Issue by ghost** [SartajBhuvaji/Brain-Tumor-Classification-Using-Deep-Learning-Algorithms#7]
Hi Sartaj, can you please provide me the annotations for segmentation purpose? 
thanks in advance

**Comment by SartajBhuvaji** [comment]
Hello @hanaelmahjoubi ,

For annotations, I used data from this [github]( https://github.com/ruslan-kl/brain-tumor.git) , however, I see that the repository is now deleted or made private

(Notebook for which is [here](https://github.com/SartajBhuvaji/Brain-Tumor-Classification-Using-Deep-Learning-Algorithms/blob/master/Tumor%20Segmentation/Brain_Tumor_Marker.ipynb) )

However, I guess you can find the annotations here. [BraTs](https://www.med.upenn.edu/sbia/brats2018.html)
